### ISSUE TITLE
1.20.1 version not compatible with neoforge

### ISSUE THREAD

**Issue by OmegaRogue** [liopyu/entityjs-geckolib4#1]
This mod seems to be dependent on forge 47.2, which is not compatible with neoforge, despite that being listed on curseforge and modrinth, causing the game to fail to launch

**Comment by liopyu** [comment]
Entityjs is run on forge 47.2.2 which is compatible with neoforge, the issue however is both the Kubejs dev and the Architectury dev have not added the neoforge tag to their most recent 1.20.1 builds resulting in kubejs to download an ancient version of neoforge kubejs and Architectury downloading a 1.21 neoforge file, it seems this is the case on both modrinth and curseforge so i'll ask both devs to add the neoforge mod tags to their most recent 1.20.1 builds so curseforge/other modpacks download the correct versions. as a temporary fix for you you can manually download their most recent FORGE 1.20.1 versions which should work with entityjs's recent version which boots up fine 
![image](https://github.com/user-attachments/assets/d414f6a1-3895-4929-beff-9910478404b0)

**Comment by liopyu** [comment]
oh i just realized this is the liolib github issues page and not the entityjs github issues page, guess this was good i misunderstood because otherwise i would not have tested out entityjs on neoforge with their builds lmao. that being said this one is and issue on my end with liolib so ill put out a fix right away

**Comment by liopyu** [comment]
matter fact if this is for AnimationJS which 1.20.1 liolib is mainly used for then the manual downloading of Kubejs/Architectury is also related since AnimationJS relys on them

**Comment by liopyu** [comment]
new versions of both liolib 0.0.8 as well as liosplayeranimatorapi 0.0.8 should be out with updated forge versionings
